### ISSUE TITLE
Config unable to connect with remote Couchbase server

### ISSUE THREAD

**Issue by stijlfigurant** [couchbase/couchbase-ruby-model#7]
Trying to run `rails generate model post`, throws error

`error  couchbase [not found]`

config/couchbase.yml:

```
common: &common
   hostname: 192.168.166.101
   port: 8091
   username:
   password:
   pool: default

development:
  <<: *common
  bucket: cbpb_development

test:
  <<: *common
  bucket: cbpb_test

# set these environment variables on your production server
production:
  hostname: <%= ENV['COUCHBASE_HOST'] %>
  port: <%= ENV['COUCHBASE_PORT'] %>
  username: <%= ENV['COUCHBASE_USERNAME'] %>
  password: <%= ENV['COUCHBASE_PASSWORD'] %>
  pool: <%= ENV['COUCHBASE_POOL'] %>
  bucket: <%= ENV['COUCHBASE_BUCKET'] %>
```

Have been running into similar issues all day (http://www.couchbase.com/forums/thread/beer-sample-rails-remote-database-servers) - can someone explain why the config is not working?

Thanks!
